languageCode = "en"
languageName = "English"
weight = 1
title = "Blarc"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2006 January 2"
# logo = "img/icon.png"
#secondaryLogo = "img/stonegarden.png"
description = "A blog about techonology and other hobbies."
# copyright = "Copy, _right?_ :thinking_face:"

[params.author]
name = "Jakob Male탑i훾"
image = "img/blarc_avatar.jpeg"
headline = "DevOps engineer and a passionate developer of side projects."
bio = "DevOps developer"
links = [
    { email = "mailto:jakob.malezic@gmail.com" },
    #     { link = "https://link-to-some-website.com/" },
    #     { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
    #     { apple = "https://www.apple.com" },
    #     { blogger = "https://username.blogspot.com/" },
    #     { codepen = "https://codepen.io/username" },
    #     { dev = "https://dev.to/username" },
    #     { discord = "https://discord.gg/invitecode" },
    #     { dribbble = "https://dribbble.com/username" },
    #     { facebook = "https://facebook.com/username" },
    #     { flickr = "https://www.flickr.com/photos/username/" },
    #     { foursquare = "https://foursquare.com/username" },
    { github = "https://github.com/blarc" },
    { gitlab = "https://gitlab.com/blarc" },
    #     { google = "https://www.google.com/" },
    #     { hashnode = "https://username.hashnode.dev" },
    #     { instagram = "https://instagram.com/username" },
    #     { keybase = "https://keybase.io/username" },
    #     { kickstarter = "https://www.kickstarter.com/profile/username" },
    #     { lastfm = "https://lastfm.com/user/username" },
    { linkedin = "https://linkedin.com/in/jakob-male탑i훾-ba13b5271" },
    #     { mastodon = "https://mastodon.instance/@username" },
    #     { medium = "https://medium.com/username" },
    #     { microsoft = "https://www.microsoft.com/" },
    #     { orcid = "https://orcid.org/userid" },
    #     { patreon = "https://www.patreon.com/username" },
    #     { pinterest = "https://pinterest.com/username" },
    #     { reddit = "https://reddit.com/user/username" },
    # { researchgate = "https://www.researchgate.net/profile/Vegard-Hagen" },
    #     { slack = "https://workspace.url/team/userid" },
    #     { snapchat = "https://snapchat.com/add/username" },
    #     { soundcloud = "https://soundcloud.com/username" },
    #     { stack-overflow = "https://stackoverflow.com/users/userid/username" },
    #     { steam = "https://steamcommunity.com/profiles/userid" },
    #     { telegram = "https://t.me/username" },
    #     { tiktok = "https://tiktok.com/@username" },
    #     { tumblr = "https://username.tumblr.com" },
    #     { twitch = "https://twitch.tv/username" },
    #     { twitter = "https://twitter.com/username" },
    #     { whatsapp = "https://wa.me/phone-number" },
    #     { youtube = "https://youtube.com/veghag" },
    { ko-fi = "https://ko-fi.com/blarc" },
]
